package testutil

import (
	"bytes"
	"os"
	"testing"
)

func TestWriteFixtureJPEG_IsDeterministic(t *testing.T) {
	pathA := WriteFixtureJPEG(t)
	pathB := WriteFixtureJPEG(t)

	// #nosec G304 -- test fixture paths are generated by fixture helpers.
	dataA, err := os.ReadFile(pathA)
	if err != nil {
		t.Fatalf("read fixture A: %v", err)
	}
	// #nosec G304 -- test fixture paths are generated by fixture helpers.
	dataB, err := os.ReadFile(pathB)
	if err != nil {
		t.Fatalf("read fixture B: %v", err)
	}

	if !bytes.Equal(dataA, dataB) {
		t.Fatal("fixture generation is not deterministic")
	}
}

func TestWriteFixturePNG_IsDeterministic(t *testing.T) {
	pathA := WriteFixturePNG(t)
	pathB := WriteFixturePNG(t)

	// #nosec G304 -- test fixture paths are generated by fixture helpers.
	dataA, err := os.ReadFile(pathA)
	if err != nil {
		t.Fatalf("read fixture A: %v", err)
	}
	// #nosec G304 -- test fixture paths are generated by fixture helpers.
	dataB, err := os.ReadFile(pathB)
	if err != nil {
		t.Fatalf("read fixture B: %v", err)
	}

	if !bytes.Equal(dataA, dataB) {
		t.Fatal("fixture generation is not deterministic")
	}
}
